--- cityId: "2"
cityName: "上海"
oversea: "false"
checkInDate: "2020-03-15"
checkOutDate: "2020-03-16"
head:
  cid: "09031105410759317696"
  ctok: ""
  cver: "1.0"
  lang: "01"
  sid: "8888"
  syscode: "09"
  auth:
  extension:
  - name: "allianceSid"
    value: "1693366"
  - name: "allianceId"
    value: "66672"
  - name: "awakeUnion"
    value: "{"OUID":"","AllianceID":"66672","SID":"1693366","SourceID":"","AppID":"","OpenID":""}"
  - name: "terminaltype"
    value: "20"
  - name: "devicetype"
    value: "PC"
  - name: "devicebrand"
    value: "undefined"
  - name: "devicephone"
    value: "PC"
  - name: "browsername"
    value: "Chrome"
  - name: "browserver"
    value: "80.0.3987.132"
  - name: "os"
    value: "PC"
  - name: "osver"
    value: "Windows10"
  - name: "channelid"
    value: "2"
  - name: "page"
    value: "600003543"
  - name: "refpage"
    value: "5c1a6878-0473-f2cd-7c22-2c1ead8dea3c"
  - name: "currentpage"
    value: "b803bf60-fcfb-beda-039b-492ffda6e30f"
  - name: "pagename"
    value: "hotelhome"
  - name: "refpagename"
    value: "home"
  - name: "refpageid"
    value: "600003543"
  - name: "vid"
    value: "1581673681743.jv0ex"
  - name: "la"
    value: ""
  - name: "lo"
    value: ""
  - name: "geoType"
    value: ""
  - name: "traceid"
    value: "415dfe1f-0391-5acf-5860-9546f9fc3acf"
  - name: "protocal"
    value: "https"
contentType: "json"